OrdererOrgs:
  - Name: Orderer
    Domain: terraflow.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - localhost
          - 127.0.0.1
          - orderer.terraflow.com

PeerOrgs:
  - Name: LandRegistry
    Domain: landregistry.terraflow.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - 127.0.0.1
    Users:
      Count: 1