apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "api-gateway.name" . }}
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: {{ include "api-gateway.name" . }}