apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "api-gateway.name" . }}
spec:
  type: {{ index .Values "api-gateway" "service" "type" | default "ClusterIP" }}
  ports:
  - port: {{ index .Values "api-gateway" "service" "port" | default 8081 }}
    targetPort: 8081
    {{- if and (eq (index .Values "api-gateway" "service" "type" | default "ClusterIP") "NodePort") (index .Values "api-gateway" "service" "nodePort") }}
    nodePort: {{ index .Values "api-gateway" "service" "nodePort" }}
    {{- end }}
  selector:
    app: {{ include "api-gateway.name" . }}