apiVersion: v1
kind: Service
metadata:
  name: backend-payments-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ index .Values "backend-payments" "service" "type" }}
  ports:
  - port: {{ index .Values "backend-payments" "service" "port" }}
    targetPort: 3003
    protocol: TCP
  selector:
    app: backend-payments