{{- if .Values.fabric.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fabric-orderer-msp
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    NodeOUs:
      Enable: false

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fabric-peer-msp
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    NodeOUs:
      Enable: false

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fabric-genesis
  namespace: {{ .Release.Namespace }}
data:
  genesis.block: ""
{{- end }}
