{{- if .Values.fabric.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fabric-orderer.fullname" . }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.fabric.orderer.service.type }}
  selector:
    app: {{ include "fabric-orderer.name" . }}
  ports:
  - name: orderer
    port: {{ .Values.fabric.orderer.service.port }}
    targetPort: {{ .Values.fabric.orderer.service.port }}
  - name: operations
    port: {{ .Values.fabric.orderer.service.operationsPort }}
    targetPort: {{ .Values.fabric.orderer.service.operationsPort }}
{{- end }}