apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
spec:
  replicas: {{ index .Values "frontend" "replicaCount" | default 1 }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        environment: {{ .Values.environment | default "dev" }}
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.image.repository }}/frontend:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4005
        env:
        - name: NEXT_PUBLIC_API_URL
          value: {{ index .Values "frontend" "env" "NEXT_PUBLIC_API_URL" | default "http://api-gateway-service:8081/api" | quote }}
        - name: NEXT_PUBLIC_ENVIRONMENT
          value: {{ .Values.environment | default "dev" | quote }}
