apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
spec:
  type: {{ index .Values "frontend" "service" "type" | default "ClusterIP" }}
  ports:
  - port: {{ index .Values "frontend" "service" "port" | default 4005 }}
    targetPort: 4005
    {{- if and (eq (index .Values "frontend" "service" "type" | default "ClusterIP") "NodePort") (index .Values "frontend" "service" "nodePort") }}
    nodePort: {{ index .Values "frontend" "service" "nodePort" }}
    {{- end }}
  selector:
    app: frontend
