apiVersion: v1
kind: Service
metadata:
  name: postgres-documents-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres-documents
spec:
  type: {{ .Values.postgresDocuments.service.type }}
  ports:
    - port: {{ .Values.postgresDocuments.service.port }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgres-documents