{{- if .Values.postgresUsers.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresUsers.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres-users
spec:
  type: {{ .Values.postgresUsers.service.type }}
  ports:
  - port: {{ .Values.postgresUsers.service.port }}
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres-users
{{- end }}