apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-landregistry
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-landregistry
  template:
    metadata:
      labels:
        app: postgres-landregistry
    spec:
      containers:
      - name: postgres-landregistry
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: "terraflow_landregistry"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-landregistry-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-landregistry-storage
        emptyDir: {}